services:
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_backend
    ports:
      - "5001:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    ports:
      - "3000:3000"

  db:
    image: postgres
    env_file:
      - .env
    build: 
      context: ./database
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    container_name: todo_db
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  postgres_data: