services:
  app:
    build: .
    ports:
      - "3000:3000"  # frontend
      - "5000:5000"  # backend
    volumes:
      - .:/app
      - /app/frontend/node_modules
      - /app/backend/node_modules
    command: ["sh", "-c", "serve -s frontend/build -l 3000 & npm --prefix backend run start"]