services:
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
        FRONTEND_PORT: ${FRONTEND_PORT}
    container_name: todo_backend
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/backend/src
      - /app/backend/node_modules

  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  db:
    image: postgres
    env_file:
      - .env
    build: 
      context: ./database
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    container_name: todo_db
    environment:
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: