services:
  database:
    image: postgres
    build: 
      context: .
      dockerfile: db.Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - "5432"